from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from pydantic import ValidationError

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT))

from compatibility.cases import CASES, INVALID_CASES  # noqa: E402
from compatibility.inventory import INVENTORY  # noqa: E402
from modwire_mermaid.composition import ModwireMermaidFactory  # noqa: E402
from modwire_mermaid.diagrams import DiagramAdapter  # noqa: E402

SNAPSHOTS = ROOT / "compatibility" / "snapshots" / "source"
FEATURES = ROOT / "compatibility" / "features"
DOC_DIRS = {
    "architecture": "architecture",
    "class": "class-diagram",
    "event-modeling": "event-modeling",
    "file-tree": "file-tree",
    "flowchart": "flowchart",
    "mindmap": "mindmap",
    "sequence": "sequence",
    "state": "state",
    "swimlane": "swimlanes",
    "timeline": "timeline",
    "user-journey": "user-journey",
}


def canonical_json(value: object) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def write_or_check(path: Path, content: str, check: bool, stale: list[Path]) -> None:
    if path.exists() and path.read_text() == content:
        return
    stale.append(path)
    if not check:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def render_guide(kind: str, cases: list[dict[str, Any]]) -> str:
    claims = INVENTORY[kind]
    docs_url = cases[0]["docs_url"]
    lines = [
        f"# {kind} compatibility",
        "",
        "This file is generated by `scripts/generate_compatibility.py`; do not edit it manually.",
        f"Upstream syntax: [{docs_url}]({docs_url}).",
        "The fixtures are built with strict frozen Pydantic contracts and compiled through "
        "`ModwireMermaidFactory.standard()`.",
        "",
        "## Feature inventory",
        "",
        "| Feature | Status | Contract | Evidence |",
        "| --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| `{claim.slug}` | {claim.status} | {claim.reason} | "
        f"{', '.join(f'`{item}`' for item in claim.evidence) or '—'} |"
        for claim in claims
    )
    lines.extend(("", "## Executable fixtures", ""))
    for case in cases:
        source_path = Path(case["source"])
        source = (ROOT / source_path).read_text()
        lines.extend(
            (
                f"### `{case['id']}`",
                "",
                f"Snapshot: [`{source_path.name}`](../../{source_path.as_posix()}).",
                "",
                "```mermaid",
                source.rstrip(),
                "```",
                "",
            )
        )
    if kind == "swimlane":
        lines.extend(
            (
                "## Version boundary",
                "",
                "Swimlane uses experimental `swimlane-beta` syntax and therefore requires Mermaid 11.16.0 or newer.",
                "",
            )
        )
    return "\n".join(lines).rstrip() + "\n"


def render_index(catalog: list[dict[str, Any]]) -> str:
    lines = [
        "# Mermaid compatibility evidence",
        "",
        "This file is generated by `scripts/generate_compatibility.py`; do not edit it manually.",
        "The repository tests Mermaid 11.16.0 as both the minimum and current latest supported 11.x release,",
        "using Node 24.17.0 and separately locked toolchains. `swimlane-beta` sets the minimum version.",
        "The Python distribution does not depend on Node, Mermaid CLI, Puppeteer, or Chromium.",
        "",
        "| Diagram | Minimal | Comprehensive | Guide |",
        "| --- | --- | --- | --- |",
    ]
    for kind, doc_dir in DOC_DIRS.items():
        cases = [item for item in catalog if item["kind"] == kind]
        minimal = next(item["id"] for item in cases if item["profile"] == "minimal")
        comprehensive = next(item["id"] for item in cases if item["profile"] == "comprehensive")
        lines.append(
            f"| `{kind}` | `{minimal}` | `{comprehensive}` | "
            f"[inventory and snapshots](../docs/{doc_dir}/compatibility.md) |"
        )
    lines.extend(
        (
            "",
            "Run `python scripts/generate_compatibility.py --check` for offline contract/snapshot drift, then run",
            "`node compatibility/runner.mjs minimum` and `node compatibility/runner.mjs latest-11` after installing",
            "the corresponding locked toolchains. Mermaid diagnostics and SVGs are intentionally uncommitted "
            "artifacts.",
            "",
        )
    )
    return "\n".join(lines)


def main(check: bool) -> int:
    compiler = ModwireMermaidFactory.standard()
    stale: list[Path] = []
    catalog: list[dict[str, Any]] = []
    for case in CASES:
        diagram = case.factory()
        encoded = DiagramAdapter.dump_json(diagram)
        if DiagramAdapter.dump_json(DiagramAdapter.validate_json(encoded)) != encoded:
            raise RuntimeError(f"Non-canonical JSON round trip: {case.id}")
        first = compiler.compile(diagram)
        second = compiler.compile(case.factory())
        if first != second or not first.endswith("\n") or "\r" in first:
            raise RuntimeError(f"Non-deterministic source: {case.id}")
        source_path = Path("compatibility/snapshots/source") / f"{case.id}.mmd"
        write_or_check(ROOT / source_path, first, check, stale)
        catalog.append(
            {
                "claims": list(case.claims),
                "compiler": "modwire_mermaid.composition.ModwireMermaidFactory.standard",
                "docs_url": diagram.docs_url,
                "id": case.id,
                "kind": case.kind,
                "profile": case.profile,
                "render_required": case.render_required,
                "source": source_path.as_posix(),
                "syntax_features": [
                    {"docs_slug": feature.docs_slug, "evidence_test": feature.evidence_test}
                    for feature in diagram.syntax_features
                ],
            }
        )
    for invalid in INVALID_CASES:
        try:
            invalid.factory()
        except ValidationError as error:
            first = error.errors()[0]
            if first["type"] != invalid.error_type or tuple(first["loc"]) != invalid.location:
                raise RuntimeError(f"Unexpected validation contract for {invalid.id}: {first}") from error
        else:
            raise RuntimeError(f"Invalid fixture did not fail: {invalid.id}")
    write_or_check(ROOT / "compatibility/catalog.json", canonical_json(catalog), check, stale)
    write_or_check(ROOT / "compatibility/README.md", render_index(catalog), check, stale)
    for kind, claims in INVENTORY.items():
        payload = [
            {"evidence": list(claim.evidence), "reason": claim.reason, "slug": claim.slug, "status": claim.status}
            for claim in claims
        ]
        write_or_check(FEATURES / f"{kind}.json", canonical_json(payload), check, stale)
        write_or_check(
            ROOT / "docs" / DOC_DIRS[kind] / "compatibility.md",
            render_guide(kind, [item for item in catalog if item["kind"] == kind]),
            check,
            stale,
        )
    if check and stale:
        print("Compatibility corpus is stale:")
        for path in stale:
            print(f"- {path.relative_to(ROOT)}")
        return 1
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate deterministic compatibility evidence.")
    parser.add_argument("--check", action="store_true")
    raise SystemExit(main(parser.parse_args().check))
