---
config:
  treeView:
    rowIndent: 10
    paddingX: 5
    paddingY: 5
    lineThickness: 1
    showIcons: true
    defaultIconPack: ""
    filenameIcons:
    extensionIcons:
  themeVariables:
    treeView:
      labelFontSize: "16px"
      labelColor: "currentColor"
      lineColor: "currentColor"
      iconColor: "currentColor"
      descriptionColor: "currentColor"
      highlightBg: "transparent"
      highlightStroke: "currentColor"
---
treeView-beta
    "project"/
