---
config:
  layout: tidy-tree
---
mindmap
  Root
    SQUARE["square"]
    ROUNDED_SQUARE("rounded-square")
    CIRCLE(("circle"))
    BANG))"bang"((
    CLOUD)"cloud"(
    HEXAGON{{"hexagon"}}
    Markdown["`**Unicode 猫**\nsecond line`"]
    ::icon(fa fa-book)
    :::focus
