journey
  title Customer journey 猫
  section Discover
    Step 1: 1: Customer, System
    Step 2: 2: Customer, System
    Step 3: 3: Customer, System
    Step 4: 4: Customer, System
    Step 5: 5: Customer, System
  section Adopt
    Ship: 5: Team
